twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : /cmd_vel_smoothed
        timeout : 0.5
        priority: 10
      target:
        topic   : /cmd_vel_target
        timeout : 0.5
        priority: 100
    